id: P5077C119
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Trinle Özer Series
  language: zh
  description: 'Texts by the First Dodrupchen, Jigme Trinle Özer (rdo grub ’jigs med
    phrin las ''od zer, 1745–1821), who was also known as Kunzang Shenpen (kun bzang
    gzhan phan):'
  volume:
    ef565b7220544353a1e0a789965f6015:
      title: Aspiration at the Moment of Death
      parent: Aspiration Prayers
    f1c5f8b763504ab589725e23d222267b:
      title: Brief Dharmapālas Offering
      parent: Dharma Protectors
    5ecce2666775475cb54c3ea5055d98f1:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Guru Rinpoche prayers
    03e6025286154423b44fb6636dda2bef:
      title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
        of India'
      parent: Lineage Prayers
    1c7face22f8e45afaaeb55eb956a12df:
      title: The Brief Ḍākinī Prayer
      parent: Lineage Prayers
    a0ca515f75254b90ab927d682278b8db:
      title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer
        to the Wisdom Ḍākinī Dechen Gyalmo
      parent: Lineage Prayers
    4c063cf2a9bd4c88ac69d86c4026b7cd:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    33a0f68b030b4e8a89ecc10b464f6304:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Practices
    b61d488fc74e4ab5b979c44441f22be5:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Practices
    0cac76d7e26148d7a1aaa1ef36c58706:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    e2d0fe84710946f59502bbad6a21caa8:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Sādhanas
    a578d13db13243db8d425789d86d5875:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Sādhanas
created_at: '2022-02-28T23:00:39.692444'
last_modified_at: '2022-02-28T23:00:39.692447'
